version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
#    volumes:
#      - ./full.sql:/docker-entrypoint-initdb.d/docker-init.sql
